import { NextRequest } from 'next/server';
import { requireUser } from '@/lib/api';
import type { ExtractedClaimData } from '@/lib/claims';

const escapePdfText = (value: unknown) =>
  String(value ?? '')
    .replace(/\\/g, '\\\\')
    .replace(/\(/g, '\\(')
    .replace(/\)/g, '\\)');

const formatDate = (value?: string) => {
  if (!value) return '';
  const [year, month, day] = value.split('-');
  return year && month && day ? `${month}/${day}/${year}` : value;
};

const buildUb04Fields = (claimId: string, data: ExtractedClaimData | null) => {
  const fullName = data?.patient.full_name || 'Ramesh Kumar Iyer';
  const [firstName = '', ...rest] = fullName.split(/\s+/);
  const patientName = rest.length ? `${rest.join(' ')}, ${firstName}` : fullName;

  return [
    [
      'Box 1',
      'Provider Name',
      data?.clinical.facility_name || 'Apollo Hospitals, Greams Road, Chennai',
    ],
    ['Box 3a', 'Patient Control No.', claimId],
    ['Box 4', 'Type of Bill', '111 - Inpatient Hospital'],
    [
      'Box 6',
      'Statement Covers Period',
      `${formatDate(data?.clinical.admission_date) || '05/01/2026'} - ${formatDate(data?.clinical.discharge_date) || '05/06/2026'}`,
    ],
    ['Box 8', 'Patient Name', patientName],
    ['Box 10', 'Patient DOB', formatDate(data?.patient.date_of_birth) || '03/14/1958'],
    ['Box 11', 'Patient Sex', data?.patient.gender?.charAt(0).toUpperCase() || 'M'],
    ['Box 38', 'Responsible Party', data?.insurance.plan_name || 'Apollo Munich Health Insurance'],
    ['Box 56', 'NPI', data?.clinical.hospital_npi || '1234567890'],
    ['Box 67', 'Principal Diagnosis', data?.clinical.principal_diagnosis || 'I21.0'],
    ['Box 74', 'Principal Procedure', data?.coding.cpt_codes[0]?.code || '92928'],
    ['Box 86', 'Attending Physician NPI', '9876543210'],
    ['Total Billed', 'Amount', `INR ${data?.billing.total_billed_amount || '184500'}`],
  ];
};

const createSimplePdf = (claimId: string, data: ExtractedClaimData | null) => {
  const lines = [
    'UB-04 Institutional Claim Form',
    `CMS-1450 standard layout - Claim ID ${claimId}`,
    '',
    ...buildUb04Fields(claimId, data).map(([box, label, value]) => `${box}  ${label}: ${value}`),
    '',
    'Generated by InsureFlow AI',
  ];

  const textOps = lines
    .map(
      (line, index) =>
        `BT /F1 ${index === 0 ? 18 : 11} Tf 54 ${760 - index * 24} Td (${escapePdfText(line)}) Tj ET`
    )
    .join('\n');
  const content = `${textOps}\n`;
  const objects = [
    '<< /Type /Catalog /Pages 2 0 R >>',
    '<< /Type /Pages /Kids [3 0 R] /Count 1 >>',
    '<< /Type /Page /Parent 2 0 R /MediaBox [0 0 612 792] /Resources << /Font << /F1 4 0 R >> >> /Contents 5 0 R >>',
    '<< /Type /Font /Subtype /Type1 /BaseFont /Helvetica >>',
    `<< /Length ${Buffer.byteLength(content, 'utf8')} >>\nstream\n${content}endstream`,
  ];

  let pdf = '%PDF-1.4\n';
  const offsets = [0];
  objects.forEach((object, index) => {
    offsets.push(Buffer.byteLength(pdf, 'utf8'));
    pdf += `${index + 1} 0 obj\n${object}\nendobj\n`;
  });
  const xrefOffset = Buffer.byteLength(pdf, 'utf8');
  pdf += `xref\n0 ${objects.length + 1}\n0000000000 65535 f \n`;
  pdf += offsets
    .slice(1)
    .map((offset) => `${offset.toString().padStart(10, '0')} 00000 n \n`)
    .join('');
  pdf += `trailer\n<< /Size ${objects.length + 1} /Root 1 0 R >>\nstartxref\n${xrefOffset}\n%%EOF`;

  return Buffer.from(pdf, 'utf8');
};

export async function POST(request: NextRequest) {
  const { response } = await requireUser();
  if (response) return response;

  const body = await request.json().catch(() => null);
  const claimId = String(body?.claimId || 'CLM-2852');
  const pdf = createSimplePdf(claimId, (body?.confirmedData || null) as ExtractedClaimData | null);

  return new Response(pdf, {
    headers: {
      'Content-Type': 'application/pdf',
      'Content-Disposition': `attachment; filename="${claimId}-UB04.pdf"`,
      'Content-Length': String(pdf.byteLength),
    },
  });
}
